Webkul\UVDesk\CoreBundle\Entity\Mailbox:
    type: entity
    table: null
    repositoryClass: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 191
        email:
            type: string
            length: 191
            unique: true
        mailboxEmail:
            type: string
            length: 191
            nullable: true
        isEnabled:
            type: boolean
            options:
                default: false
        isLocalized:
            type: boolean
            options:
                default: false
    lifecycleCallbacks: {  }
