Webkul\UVDesk\CoreBundle\Entity\SupportTeam:
    type: entity
    table: null
    repositoryClass: Webkul\UVDesk\CoreBundle\Repository\SupportTeamRepository
    manyToMany:
        users:
            targetEntity: UserInstance
            mappedBy: supportTeams
        leads:
            targetEntity: UserInstance
            mappedBy: leadSupportTeams
        supportGroups:
            targetEntity: SupportGroup
            mappedBy: supportTeams
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 191
        description:
            type: text
        createdAt:
            type: datetime
        isActive:
            type: boolean
            options:
                default: false
    lifecycleCallbacks:
        prePersist: [ initializeTimestamp ]
