helpdesk_member_dashboard:
    path:     /dashboard
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Account::loadDashboard

helpdesk_member_profile:
    path:     /profile
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Account::loadProfile
    defaults: { panelId: 'account' }

helpdesk_member_account_xhr:
    path:     /agent/xhr/{agentId}
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\AccountXHR::deleteAgent
    defaults: { panelId: 'users', agentId: 0 }

helpdesk_member_account:
    path:     /agent/{agentId}
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Account::editAgent
    defaults: { panelId: 'users', agentId: 0 }

helpdesk_member_account_collection:
    path:     /agents
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Account::listAgents
    defaults: { panelId: 'users' }

helpdesk_member_account_collection_xhr:
    path:     /agents/xhr
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\AccountXHR::listAgentsXHR

helpdesk_member_create_account:
    path:     /create/agent
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Account::createAgent
    defaults: { panelId: 'users' }

helpdesk_member_forgot_account_password:
    path:     /forgot-password
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Account::forgotPassword

helpdesk_member_saved_filters_xhr:
    path:     /saved-filter-xhr/{filterId}
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\AccountXHR::savedFiltersXHR
    defaults: { filterId: 0 }

# Support Group Resources
helpdesk_member_support_group_collection:
    path:     /groups
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Group::listGroups
    defaults: { panelId: 'users' }

helpdesk_member_support_group_collection_xhr:
    path:     /groups/xhr
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\GroupXHR::listGroupsXHR
    defaults: { panelId: 'users' }

helpdesk_member_create_support_group:
    path:     /create/group
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Group::createGroup
    defaults: { panelId: 'users'}

helpdesk_member_update_support_group:
    path:     /group/{supportGroupId}
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Group::editGroup
    defaults: { panelId: 'users'}

helpdesk_member_remove_support_group_xhr:
    path:      /group/delete/xhr/{supportGroupId}
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\GroupXHR::deleteGroupXHR
    defaults:  {panelId: 'users', supportGroupId: 0 }

# Support Team Resources
helpdesk_member_support_team_collection:
    path:     /teams
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Team::listTeams
    defaults: { panelId: 'users' }

helpdesk_member_support_team_collection_xhr:
    path:     /teams/xhr
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\TeamXHR::listTeamsXHR
    defaults: { panelId: 'users' }

helpdesk_member_create_support_team:
    path:     /create/team
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Team::createTeam
    defaults: { panelId: 'users'}

helpdesk_member_update_support_team:
    path:     /team/{supportTeamId}
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Team::editTeam
    defaults: { panelId: 'users'}

helpdesk_member_remove_support_team_xhr:
    path:     /team/delete/xhr/{supportTeamId}
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\TeamXHR::deleteTeamXHR
    defaults: { panelId: 'users', supportTeamId: 0}

# Support Privilege Resources
helpdesk_member_privilege_collection:
    path:     /privileges
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Privilege::listPrivilege
    defaults: { panelId: 'users'}

helpdesk_member_privilege_collection_xhr:
    path:     /privileges/xhr
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\PrivilegeXHR::listPrivilegeXHR
    defaults: { panelId: 'users' }

helpdesk_member_create_privilege:
    path:     /create/privilege
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Privilege::createPrivilege
    defaults: { panelId: 'users'}

helpdesk_member_update_privilege:
    path:     /privilege/{supportPrivilegeId}
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Privilege::editPrivilege
    defaults: { panelId: 'users'}

helpdesk_member_remove_privilege_xhr:
    path:     /privilege/delete/xhr/{supportPrivilegeId}
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\PrivilegeXHR::deletePrivilegeXHR
    defaults: { panelId: 'users', supportPrivilegeId: 0}
customer_mark_star_action:
    path:     /update-star
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\Customer::updateStar
    defaults: { panelId: 'users', id: 0}


# User Profile
edit_profile:
    path:     /profile
    # defaults: { _controller: UVDeskSupportBundle:UserActivity:editProfile}
    controller: Webkul\UVDesk\SupportBundle\Controller\UserActivityController::editProfile
    defaults: { panelId: 'usersprofile' }

access_token_xhr:
    path:     member/access-token
    defaults: { _controller: UVDeskSupportBundle:Api:accessTokenXhr }
    methods: [GET,POST]
helpdesk_member_saved_filters_xhr:
    path:     /saved-filter-xhr/{filterId}
    controller: Webkul\UVDesk\SupportBundle\Controller\Members\AccountXHR::savedFiltersXHR
    defaults: { filterId: 0 }


