uvdesk:
    site_url: localhost
    upload_manager:
        id: uvdesk.core.fs.upload.manager
    
    support_email: ~
    
    # Default resources
    default:
        ticket:
            type: ~
            status: ~
            priority: ~
        templates:
            email: mail.html.twig
    
    # Configure your mailboxes here
    mailboxes: ~
        # default:
        #     name: 'Sample Mailbox'
        #     enabled: true
        
        #     # [SMTP] Outgoing mail server
        #     # Swiftmailer smtp mailer to use for sending emails through on behalf of this mailbox
        #     smtp_server:
        #         mailer_id: ~
        
        #     # [IMAP] Incoming mail server
        #     # IMAP configurations to use for fetching emails from mailbox
        #     imap_server:
        #         host: ~
        #         email: ~
        #         password: ~
