<?php

namespace Webkul\UVDesk\CoreBundle\Fixture;

use Doctrine\Common\Persistence\ObjectManager;
use Webkul\UVDesk\CoreBundle\Entity as CoreEntities;
use Doctrine\Bundle\FixturesBundle\Fixture as DoctrineFixture;

class EmailTemplate extends DoctrineFixture
{
    private static $seeds = [
        [
            'name' => 'Customer Reply To The Agent',
            'subject' => 'Customer Reply Ticket #{% ticket.id %}',
        ],
        [
            'name' => 'Agent Reply To The Customer\'s ticket',
            'subject' => 'New Reply Added on ticket #{% ticket.id %}',
        ],
        [
            'name' => "Ticket Assign",
            'subject' => 'Ticket #{% ticket.id %} assign to you',
        ],
        [
            'name' => "Member Added In Task",
            'subject' => 'Member Added In Task',
        ],
        [
            'name' => "Customer Forgot password",
            'subject' => 'Customer Forgot password',
        ],
        [
            'name' => "Ticket generated by agent",
            'subject' => 'A ticket has been generated by agent',
        ],
        [
            'name' => "Ticket generated by customer",
            'subject' => 'A new ticket #{% ticket.id %} has been generated by {% ticket.customerName %}',
        ],
        [
            'name' => "Collaborator added reply",
            'subject' => 'Ticket collaborator added reply in ticket {%ticket.id%}',
        ],
        [
            'name' => "Collaborator added to ticket",
            'subject' => 'A new Collaborator have been added.',
        ],
        [
            'name' => "Mail to the collaborator",
            'subject' => 'Mail to the collaborator',
        ],
        [
            'name' => "Task Created",
            'subject' => 'A new task #{% task.id %} is assigned to you.',
        ],
        [
            'name' => "Member Reply in Task",
            'subject' => 'Member Reply In Task #{% task.id %}',
        ],
        [
            'name' => "Agent Forgot Password",
            'subject' => 'Agent Forgot Password',
        ],
        [
            'name' => "Ticket Generate Success Mail For Customer",
            'subject' => 'Congo!! Ticket generation process accomplished.',
        ],
        [
            'name' => "Long Pending Ticket",
            'subject' => 'Waiting for response on the ticket.',
        ],
        [
            'name' => "Account Activation",
            'subject' => 'Success!!! Account has been created.',
        ],
        [
            'name' => "Customer Forgot password",
            'subject' => 'Customer Forgot password',
        ],
    ];

    public function load(ObjectManager $entityManager)
    {
        $availableEmails = $entityManager->getRepository('UVDeskCoreBundle:EmailTemplates')->findAll();

        // if (count($availableEmails) <= 0) {
        //     foreach (self::$seeds as $email)
        //     {
        //         $template = new CoreEntities\EmailTemplates();
        //         $template->setName($email['name']);
        //         $template->setSubject($email['subject']);
        //         $template->setMessage($email['message']);
        //         $template->setMessageInline($email['messageInline']);

        //         $entityManager->persist($template);
        //         $entityManager->flush();
        //     }
        // }
    }
}
